"""Initial tables

Revision ID: 21adf08c7578
Revises: 
Create Date: 2025-08-01 21:00:55.403016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21adf08c7578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('import', 'export'), nullable=False),
    sa.Column('container_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'customs_hold', 'cleared', 'delivered'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('customs_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    op.drop_table('user')
    # ### end Alembic commands ###
